# Generated by Django 4.1.7 on 2023-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_category_url_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='view',
            new_name='file_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(default='', max_length=225),
        ),
    ]
