# Generated by Django 4.1.7 on 2023-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_remove_document_cat_remove_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.IntegerField(max_length=50),
        ),
    ]
