# Generated by Django 4.1.7 on 2023-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_document_file_type_alter_document_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.IntegerField(max_length=100),
        ),
    ]
