# Generated by Django 4.1.7 on 2023-04-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.CharField(default='ГОСТ', max_length=100),
        ),
    ]
