# Generated by Django 4.1.7 on 2023-04-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_document_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
