# Generated by Django 4.1.7 on 2023-04-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_remove_document_text_remove_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(default='', max_length=225)),
                ('url', models.CharField(default='/', max_length=40)),
                ('size', models.IntegerField(default='', max_length=100)),
                ('file_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
