# Generated by Django 4.1.7 on 2023-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_gost_delete_category_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gost',
            name='description',
            field=models.CharField(default='-', max_length=225),
        ),
        migrations.AlterField(
            model_name='gost',
            name='file_type',
            field=models.CharField(default='pdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='gost',
            name='size',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
