# Generated by Django 4.1.7 on 2023-04-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_alter_gost_description_alter_gost_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gost',
            name='url',
        ),
    ]
