# Generated by Django 4.1.7 on 2023-04-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_gost_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gost',
            old_name='url',
            new_name='сategory',
        ),
    ]
