# Generated by Django 4.1.7 on 2023-04-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_rename_url_gost_сategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gost',
            old_name='сategory',
            new_name='url',
        ),
    ]
