# Generated by Django 4.1.7 on 2023-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_rename_сategory_gost_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gost',
            name='url',
            field=models.CharField(default='gost', max_length=225),
        ),
    ]
